### ISSUE TITLE
'Use above settings for server' is ignored for an external file

### ISSUE THREAD

**Issue by MikeUnwalla** [danielnaber/oxygen-languagetool-plugin#8] opened 2016-12-02 13:57 UTC
In LanguageTool Options, when 'Use above settings for server' is selected, the LanguageTool Check in oXygen does not use the settings that are specified for rules that are in an external file (http://wiki.languagetool.org/tips-and-tricks#toc10).

![oxygen-external-rule-not-ignored](https://cloud.githubusercontent.com/assets/5816160/20836186/21330c9a-b896-11e6-9e7a-4455ced7f55c.png)

I noticed this problem using LT 3.5 and LT 36 snapshot, and oXygen 18.1 (I haven't used oXygen and LT for many months, so I don't know when the problem was introduced).

**Comment by danielnaber** [comment] 2016-12-03 14:23
Are you sure you're using the same language for both stand-alone GUI and oxygen? For oxygen, the document language is used. The the country code also needs to be the same. If you make settings in the stand-alone GUI for `en-GB`, this is exactly what needs to be your document language in oxygen for the settings to become active.

**Comment by MikeUnwalla** [comment] 2016-12-03 17:25
Problem solved. I must close both oXygen _and_ LT and start them again for oXygen to use only the activated rules.

In oXygen, in Options>Preferences>Editor>Spell Check, the 'Default language' option was `English` and  'Use "lang" and "xml:lang" attributes' was selected. I changed 'Default language' to `English (US)`, but the problem _sometimes_ remained.

In the GUI, if the rule in the external file (which finds 'test') is deactivated, and I activate the rule, then in oXygen, when I click LanguageTool Check, the rule finds 'test'.

If I deactivate the rule in the GUI, and check the text in oXygen, 'test' remains highlighted.

If I close oXygen and start it again, when I check the text, 'test' is highlighted, although the rule is deactivated in the GUI.

But, if I close oXygen and LT, and then start them both, 'test' is not highlighted in oXygen.

**Comment by MikeUnwalla** [comment] 2016-12-03 18:33
If the language is not specified in the file using 'lang' or 'xml:lang', LT does not ignore deactivated rules. The screen shot shows the standard LT 3.5 (no external file). 
![oxygen-deactivated-rule-not-ignored](https://cloud.githubusercontent.com/assets/5816160/20861370/5daa5b42-b986-11e6-975a-937340fd28b7.png)

**Comment by danielnaber** [comment] 2016-12-03 20:07
Trying to reproduce this I found a bug that might also be the cause for your problem: the configuration data (i.e. the default language) in oxygen 18.0 was loaded from an old configuration file of oxygen 16.0. If you still have oxygen 16.0 around, you can change the default language there. This will be fixed in the next release of the add-on.

**Closed** 2017-03-03 16:49 UTC
